/**
 * Blog Data Source for Science & Technology Articles
 * Author: Noppasin Pronsawad
 * Supports optional `image` property per post. If `image` is present, it renders an image header/thumbnail.
 */

const BLOG_POSTS = [
  // ==========================================================================
  // Science Blog Articles
  // ==========================================================================
  {
    id: "science-1",
    category: "Science",
    date: "Aug 2026",
    readTime: "5 min read",
    title: "The Evolution of Silicate Weathering and Carbon Sequestration",
    summary: "An exploration of geological processes and their role in capturing atmospheric carbon over millions of years.",
    image: "assets/images/silicate_weathering.png",
    content: `
      <h3>Introduction</h3>
      <p>Silicate weathering plays a critical role in Earth's long-term carbon cycle. Over millions of years, the chemical breakdown of silicate minerals by carbonic acid removes carbon dioxide from the atmosphere, depositing it in oceanic carbonate sediments.</p>

      <h3>Mechanism of Chemical Weathering</h3>
      <p>When atmospheric carbon dioxide dissolves in rainwater, it forms weak carbonic acid (H₂CO₃). This acidic rainfall reacts with exposed basalt and granite rocks on land, dissolving silicate minerals into calcium, magnesium, and bicarbonate ions (HCO₃⁻).</p>

      <pre><code>CaSiO₃ + 2CO₂ + H₂O ➔ Ca²⁺ + 2HCO₃⁻ + SiO₂</code></pre>

      <p>Rivers transport these dissolved ions to rivers and oceans, where marine organisms like foraminifera and corals utilize calcium and bicarbonate to build calcium carbonate (CaCO₃) shells. Upon death, these organisms settle on the ocean floor, effectively locking carbon in sedimentary rock for tectonic timescales.</p>

      <h3>Enhanced Weathering & Energy Transition</h3>
      <p>In modern climate geoscience, scientists are researching <em>Enhanced Rock Weathering (ERW)</em>—spreading finely ground basaltic dust over agricultural soil to accelerate natural carbon dioxide absorption while improving soil fertility.</p>
    `
  },
  {
    id: "science-2",
    category: "Science",
    date: "Jul 2026",
    readTime: "6 min read",
    title: "Physics of Flight: Understanding Modern Aircraft Dynamics",
    summary: "Breaking down the complex aerodynamic principles and cockpit instrumentation that keep advanced aircraft in the sky.",
    image: "assets/images/aircraft_aerodynamics.png",
    content: `
      <h3>Four Forces of Flight</h3>
      <p>Flight relies on a continuous balance between four fundamental physical forces: <strong>Lift</strong>, <strong>Weight</strong>, <strong>Thrust</strong>, and <strong>Drag</strong>. Lift is generated by airfoil geometry obeying Bernoulli’s principle and Newton’s third law of motion.</p>

      <h3>Airfoil Aerodynamics</h3>
      <p>As airflow splits around a wing, air moving over the curved upper surface accelerates, creating lower pressure relative to the flat under-wing surface. This pressure differential generates aerodynamic lift directed upward perpendicular to flight direction.</p>

      <h3>Cockpit Avionics & Angle of Attack</h3>
      <p>Maintaining controlled flight requires monitoring the <em>Angle of Attack (AoA)</em>—the angle between the wing chord line and relative wind velocity. Modern glass cockpits utilize Pitot-Static systems and air data computers to prevent aerodynamic stalls and ensure precise envelope protection.</p>
    `
  },
  {
    id: "science-3",
    category: "Science",
    date: "Jun 2026",
    readTime: "7 min read",
    title: "Modern Petroleum Geoscience in the Energy Transition",
    summary: "How traditional geological analysis and well logging adapt to the shifting landscape of global energy demands.",
    image: "assets/images/petroleum_geoscience.png",
    content: `
      <h3>Subsurface Modeling in the Modern Era</h3>
      <p>Petroleum geoscience methodologies—such as 3D seismic interpretation, petrophysical log integration, and reservoir geometry mapping—are undergoing a transformation. The analytical tools developed for hydrocarbon exploration are now being redeployed for geothermal energy and Carbon Capture & Storage (CCS).</p>

      <h3>Subsurface Reservoir Trapping Mechanics</h3>
      <p>Carbon capture requires deep saline aquifers or depleted reservoirs sealed by impermeable caprocks (such as thick shale layers). High-resolution seismic modeling techniques previously used to map Gulf of Thailand reservoirs are directly applicable to evaluating seal integrity for permanent CO₂ geological storage.</p>

      <h3>Integrating Data & Geomechanics</h3>
      <p>Combining well log data (gamma ray, resistivity, density neutron) with reservoir simulation algorithms ensures safe pressure limits during fluid injection, preventing fault reactivation and ensuring long-term containment.</p>
    `
  },
  {
    id: "science-4",
    category: "Science",
    date: "May 2026",
    readTime: "4 min read",
    title: "Aviation Meteorology: Navigating Complex Weather Patterns",
    summary: "The science behind interpreting meteorological charts for safe and efficient flight planning.",
    image: "assets/images/aviation_meteorology.png",
    content: `
      <h3>Understanding Atmospheric Turbulence & Fronts</h3>
      <p>Aviation meteorology focuses on atmospheric dynamics that directly impact flight safety. Pilots and dispatchers analyze METAR, TAF, and SIGMET reports to identify convective activity, icing conditions, and Clear Air Turbulence (CAT).</p>

      <h3>Jet Streams & Flight Route Optimization</h3>
      <p>Jet streams—narrow bands of strong wind in the upper troposphere—can reach speeds over 200 knots. Navigating with tailwinds dramatically reduces fuel consumption, while avoiding shear zones prevents structural strain and passenger discomfort.</p>
    `
  },

  // ==========================================================================
  // Technology Blog Articles
  // ==========================================================================
  {
    id: "tech-1",
    category: "Technology",
    date: "Aug 2026",
    readTime: "6 min read",
    title: "Bridging the Gap: Effective Requirements Analysis in Fintech",
    summary: "Methodologies for translating complex financial and banking needs into actionable technical requirements.",
    image: "assets/images/fintech_requirements.png",
    content: `
      <h3>The FinTech Alignment Challenge</h3>
      <p>In high-compliance banking environments, bridging business goals with technical software execution requires precise specification. Business Analysts act as translators between compliance officers, treasury managers, and software engineers.</p>

      <h3>Structuring Functional & Technical Specifications</h3>
      <p>Successful API gateway integrations (such as BAHTNET or E-Wallet engines) rely on clear sequence diagrams, open API schemas, data mapping matrices, and exception-handling rules.</p>

      <h3>Key Steps for High-Impact BA Delivery</h3>
      <ul>
        <li><strong>Stakeholder Discovery:</strong> Mapping end-to-end operational workflows and pain points.</li>
        <li><strong>API Specification:</strong> Defining payload parameters, authentication headers, and HSM cryptographic requirements.</li>
        <li><strong>UAT Execution:</strong> Establishing test matrices and validation scenarios before production go-live.</li>
      </ul>
    `
  },
  {
    id: "tech-2",
    category: "Technology",
    date: "Jul 2026",
    readTime: "5 min read",
    title: "Automating Workflows with Python and GitHub Bots",
    summary: "A practical guide to integrating custom Discord and Telegram bots with GitHub actions for seamless CI/CD monitoring.",
    image: "assets/images/python_github_bots.png",
    content: `
      <h3>Streamlining Developer Operations</h3>
      <p>Automating back-office and deployment notifications keeps development teams aligned without manual status checking. Using lightweight Python scripts and webhook endpoints, developers can automate CI/CD pipeline alerts directly into team communication channels.</p>

      <h3>Building Webhook Event Handlers</h3>
      <p>Using frameworks like FastAPI or Flask in combination with asynchronous requests allows instant processing of GitHub push, pull request, and release events.</p>

      <pre><code>@app.post("/webhook/github")
async def handle_github_event(request: Request):
    payload = await request.json()
    event_type = request.headers.get("X-GitHub-Event")
    # Dispatch notification to Discord/Telegram
    return {"status": "success"}</code></pre>

      <h3>Measurable Workload Cut</h3>
      <p>Automating routine deployment verification and build notifications reduces manual monitoring workload by up to 30%, speeding up incident response time.</p>
    `
  },
  {
    id: "tech-3",
    category: "Technology",
    date: "Jun 2026",
    readTime: "6 min read",
    title: "Evaluating AI Models in Modern Software Engineering",
    summary: "Strategies for implementing and testing LLM-driven tools to enhance development velocity and code quality.",
    image: "assets/images/ai_software_engineering.png",
    content: `
      <h3>AI-Assisted Development Paradigm</h3>
      <p>Generative AI tools and specialized coding agents are revolutionizing how engineering teams write, refactor, and audit software. However, evaluating these tools requires rigorous quality benchmarks rather than superficial speed metrics.</p>

      <h3>Evaluation Benchmarks & Code Safety</h3>
      <p>When integrating AI coding assistants into enterprise workflows, teams must enforce strict linting, automated unit testing, and human-in-the-loop security audits to prevent hallucinations and unhandled edge cases.</p>
    `
  },
  {
    id: "tech-4",
    category: "Technology",
    date: "May 2026",
    readTime: "5 min read",
    title: "Data-Driven Strategies: Automating DCA for US ETFs",
    summary: "Building scripts to monitor, simulate, and automate Dollar Cost Averaging strategies in the stock market.",
    image: "assets/images/dca_stock_automation.png",
    content: `
      <h3>Dollar Cost Averaging (DCA) Automation</h3>
      <p>Automating investment strategies eliminates emotional bias in market participation. Python scripts integrated with financial market APIs enable systematic execution of DCA for broad-market US ETFs.</p>

      <h3>Backtesting & Data Analysis</h3>
      <p>Using Pandas and NumPy, historical market data can be simulated across different market cycles (bull, bear, and consolidation) to evaluate drawdown risk and portfolio compounding speed.</p>
    `
  }
];
